DB is_valid_name(): qualify func names
When trying a pg_dump + psql restore of the "cdn" database I ran into
errors stating `ERROR: function is_valid_dns_label(text) does not exist`.
The reason for this is that the pg_dump output file contains:
```
SELECT pg_catalog.set_config('search_path', '', false);
```
which clears the search_path, and with no search_path it is not clear
what function is referenced. For this reason update `is_valid_name()` to
qualify contained function calls in with the "cdn" schema name.

This migration broke the local tests:
```
ERROR: schema "cdn" does not exist (SQLSTATE 3F000)
```

So also update the test code to create the schema (together with a
matching "cdn" user) and start interacting with the test databases as
that user so the search_path logic is handled the same as in our real DB
servers.