go fix ./...
Needed manual tweak to make modifed check for http.MaxBytesError actually
use the mbe err value, otherwise errcheck was unhappy:
```
pkg/server/server.go:1127:6: Error return value of `errors.AsType` is not checked (errcheck)
		if _, ok := errors.AsType[*http.MaxBytesError](err); ok {
```

We just use mbe.Error() as the string returned to the user to make it
work for now. It seems maybe errcheck should ideally be happy without
the use of mbe since we do act on the "ok" in either case.