Support keycloak client credential API tokens
This adds support for using "API tokens" when authenticating to the API.
When requesting a new API token the system will contact the keycloak
"client registration service" using an admin client credential which has
permissions to create new clients.

On successful client creation this is recorded in the database including
the "Registration Access Token" which can be used for further management
of the newly created client (e.g. deleting it if requested). This is how
we get away with only giving "create-client" permissions to the admin
client rather than "manage-clients" while still being able to delete
any client it has created.

The registration access token is encrypted using XChaCha20-Poly1305 and
includes the related database UUID as additional data to protect against
swapping ciphertexts between rows to have the system somehow decrypt
someone elses registration token.

Make client credential access tokens contain an "aud" value of
"sunet-cdn-manager" so we can tell that the access token we recieve
was meant for our service. The requires modifying the local-dev
scripts to create client-scope and related mapper to insert it.

Add JWT token validation function for verifying the access token,
as well as creating AuthData struct based on the JWT content. This is
used in the huma auth middleware to accept requests using the keycloak
access tokens. This also requires making the Username and UserID fields
in the struct pointers since an API token is bound to an org rather than
a specific user.

Also make prepareServer() used in tests take struct with input data
instead of individual parameters. Makes it much easier to add new input
items without having to modify the call for all tests.

While here upgrade testcontainers-go:
===
After adding the new testcontainer for keycloak running
`go test -race ./...` would fail like so (not that it is the already
existing test that failed, not our new one):
```
--- FAIL: TestPostServiceVersion (0.05s)
    server_test.go:3344: create container: reaper: container state: Error response from daemon: No such container: 57462ae8987bf6f9deff92b9bdc455cc1fac6de7075d4bb93af6381553e59fcd
        terminate: stop: container stop: Error response from daemon: No such container: 57462ae8987bf6f9deff92b9bdc455cc1fac6de7075d4bb93af6381553e59fcd
```

It seems the container ID it was looking for was the ryuk reaper container
that handles cleanup.

Running tests without -race did not show the problem.

Upgrading seems to fix it so -race works again:
```
go get github.com/testcontainers/testcontainers-go
go mod tidy
```
===

Finally there are several misc fixes for things noticed while working on
this.